apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta property="og:title" content="Sample Page">
      <meta property="og:description" content="A short example with Open Graph tags.">
      <meta property="og:type" content="website">
      <meta property="og:url" content="https://example.com/sample">
      <meta property="og:image" content="https://example.com/og-image.jpg">
    </head>
    <body>
      <h1>Hello Buddy Enjoy Devops</h1>
    </body>
    </html>
